"$schema" = "https://ubcode.useblocks.com/ubproject.schema.json"

[server]
index_on_save = true

[needs]
id_required = true
id_regex = "^[A-Z0-9_]{3,}"
schema_severity = 'warning'

[needs.string_links.codelinks]
regex = "^(?P<prefix>[^/]+//[^/]+/[^/]+/[^/]+/[^/]+/[^/]+/)(?P<remains>.*)?"
link_url = "{url}"
link_name = "{{remains}}"
options = ["remote_url"]

[[needs.extra_options]]
name = "efforts"
description = "FTE days"
schema.type = "integer"
schema.minimum = 0

[[needs.extra_options]]
name = "asil"
description = "Automotive Safety Integrity Level"
schema.type = "string"
schema.enum = ["QM", "A", "B", "C", "D"]

[[needs.extra_options]]
name = "remote_url"
description = "CodeLinks marker for remote URL"
schema.type = "string"
